[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001857CB30550>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/85ffd0986f6d6cd237885617901dc56c/url
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001857CB307D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/85ffd0986f6d6cd237885617901dc56c/url
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001857CA922C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/85ffd0986f6d6cd237885617901dc56c/url
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001857CAABCE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/85ffd0986f6d6cd237885617901dc56c
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001857CF2C050>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/85ffd0986f6d6cd237885617901dc56c
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001857CF2C380>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/85ffd0986f6d6cd237885617901dc56c