[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E429064690>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/1d99f52fd31b84cba9a920b60d572379/url
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E429064910>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/1d99f52fd31b84cba9a920b60d572379/url
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E428F0A2C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/1d99f52fd31b84cba9a920b60d572379/url
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E42913C270>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/1d99f52fd31b84cba9a920b60d572379
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E42913C5A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/1d99f52fd31b84cba9a920b60d572379
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E42913C8D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/1d99f52fd31b84cba9a920b60d572379